#!/bin/bash
#
# Jonas Colmsjö 2012-08-19
#
# Deploy the configuration files for a specific AWS account. The parameter
# specifies the folder for the configuration files to use
#

cp $1/vtiger/config.inc.php ../lib/vtiger-5.4.0
