#!/bin/bash
#
# Jonas Colmsjö 2012-08-19
#
# Deploy the configuration files for a specific AWS account. The parameter
# specifies the folder for the configuration files to use
#
if [ -n "$1" ]
then
    echo Usage: ./deploy-configuaration [[region]] [[memcache-location]]
fi
cp $1/vtiger/config.inc.php ../lib/vtiger-5.4.0
cp $1/phpMyAdmin/config.inc.php ../lib/phpMyAdmin-3.5.2-all-languages
if [ -n "$2" ]
then
    cp $1/rest-api/main.php ../api/protected/config
else
    cp $1/rest-api/main-$2memcache.php /api/protected/config/main.php 
fi
cp $1/.htaccess ../.htaccess
