#!/bin/bash
#
# Jonas Colmsjö 2012-08-19
#
# Deploy the configuration files for a specific AWS account. The parameter
# specifies the folder for the configuration files to use
#
if [ -n "$1" ]
then
    echo Pushing $1
else

	# Show usage and exit

    echo Usage: ./push-new-version [region]
    exit 0
fi


chmod +x deploy-configuration
./deploy-configuration $1
git commit -a -m "Updated configuration with $1"
git aws.push
