#!/bin/bash


if [ -n "$1" ]
then
    echo All Good
else
    echo Usage: ./deploy-configuaration [[region]] [[memcache-location]]
fi

echo "vtiger configuration...."
grep "db_server"   $1/vtiger/config.inc.php
grep "db_port"     $1/vtiger/config.inc.php
grep "db_username" $1/vtiger/config.inc.php
grep "db_password" $1/vtiger/config.inc.php
grep "db_name"     $1/vtiger/config.inc.php
