<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2 setup script
 * Date: Tue, 02 Oct 2012 12:08:45 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: gc1-mysql1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'gc1-mysql1';
$cfg['Servers'][$i]['host'] = 'gc1-mysql1.cjd3zjo5ldyz.eu-west-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '506ad877d6e546.86700785';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
//$cfg['ForceSSL'] = true;
$cfg['UserprefsDeveloperTab'] = true;
$cfg['Error_Handler']['display'] = true;
$cfg['Error_Handler']['gather'] = true;
$cfg['DBG']['sql'] = true;
?>
